# Generated by Django 5.2.4 on 2025-11-10 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="criado_em",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 11, 10, 18, 24, 40, 86994, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="produtos/"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="produto",
            name="url_imagem",
            field=models.URLField(blank=True, null=True),
        ),
    ]
