# Generated by Django 5.2.4 on 2025-11-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_produto_atualizado_em_produto_criado_em_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="url_imagem",
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
