# Generated by Django 5.2.4 on 2025-12-06 21:44

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_produto_url_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to=product.models.gerar_nome_unico_imagem
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="url_imagem",
            field=models.URLField(blank=True, null=True),
        ),
    ]
